# Generated by Django 3.1.7 on 2021-04-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
